
name: Drift Monitor

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  check-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect Drift
        run: |
          python scripts/log_features.py
          python scripts/drift_detector.py
          python scripts/alerts.py
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
